name: deploy_to_AWS_S3

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Hello World!
        run: echo "hello world"
      - uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16.19.1
      - name: Install Node Dependencies
        run: npm install
      - name: Build React App
        run: npm run build
      - name: Show files
        run: ls
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: AKIARPCHKOKOWWEFNZDL
          aws-secret-access-key: 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
          aws-region: us-east-1